name: Daily Deal Scraper
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-scraper]
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./scraper
        run: |
          npm install
          npx playwright install chromium

      - name: Create Credentials File
        working-directory: ./scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDS" > credentials.json

      - name: Run Scraper
        working-directory: ./scraper
        env:
          # תופס את הדגל שנשלח מגוגל שיטס ומעביר אותו ל-Node.js
          UPDATE_ONLY_EMPTY: ${{ github.event.client_payload.updateEmptyOnly }}
        run: node run.js